#!/bin/bash

dataset=~/winequality-red.csv
firstFile=./wine/train/data.csv
secondFile=./wine/test/data.csv

total=$(($(wc -l < $dataset) - 1))
first=$(($total * 80 / 100))
second=$(($total - $first))

#store the first 80% into first file (also add header) (wc -l = 1280)
head -1 $dataset > $firstFile
head -$(($first+1)) $dataset | tail -$first >> $firstFile

#store the second 20% into the second file (also add header) (wc -l = 321)
head -1 $dataset > $secondFile
tail -$second $dataset >> $secondFile

awk -f ./bin.awk $firstFile > ./wine/train/clean_data.csv
awk -f ./bin.awk $secondFile > ./wine/test/clean_data.csv

#i=0
#while read line
#do
#	if [$i -eq 0]
#	then
#		HEAD=$line
#	elif [$i -eq $(($second+1))]
#	then
#		echo $HEAD > $secondFile
#	fi
#done < $dataset
